### ISSUE TITLE
Test Syncing Pivotal Tracker with GitHub

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-js#4802]
**Is your feature request related to a problem? Please describe.**

Amplify sprints & projects are managed internally via Pivotal Tracker, while work takes place in GitHub.

**Describe the solution you'd like**

With the intent to have a public project board that has visibility within Amazon and the Amplify community, GitHub should be bidirectionally synced with Pivotal Tracker.

Via webhooks, GitHub issues & milestones will be synced to https://www.pivotaltracker.com/n/projects/2431346.

**Describe alternatives you've considered**

ZenHub provides planning & metrics, but would pose significant risk with losing existing KPIs we rely on.

---

### Open Questions

- ~~What do GitHub issues equate to? Pivotal Stories?~~
- What do GitHub PRs equate to? Links/Attachments in Pivotal Stories?
- ~~What do GitHub Milestones equate to? Pivotal Epics?~~
- ~~What do GitHub labels equate to? Pivotal Labels?~~
- What does Pivotal Story Points equate to? (Nothing)
- ~~What do Pivotal Epics equate to? (GitHub Milestone? Single GitHub Issue with Epic label?)~~
- How to equate Pivotal Story Status with Issues/PRs?
- How to associate PR’s associate Issue with Pivotal?

### Prototype

- [x] ~~CLI to run some commands manually?~~
- [x] Simple HTTP server (arc.codes? amplify function? There’ll be fallout if I don’t use Amplify)
- [x] Local end-point testing? (ngrok?)
  - https://developer.github.com/webhooks/configuring/
- [ ] Pivotal webhook.
- [x] GitHub webhook.

### Use-Cases

- [x] When a New GitHub Issue is created, create a Pivotal Story with `external_id`.

	The problem here is that `external_id` requires an `integration_id`, so an integration must exist already to link the two together.  Plus, only the API token for the project creator can create stories via the API.

	Pivotal:
	> ![Screen Shot 2020-01-29 at 4 48 39 PM](https://user-images.githubusercontent.com/15182/73410613-a4d39700-42b7-11ea-8607-9992935c9da4.png)

	ngrok:
	> ![Screen Shot 2020-01-29 at 4 51 11 PM](https://user-images.githubusercontent.com/15182/73410614-a4d39700-42b7-11ea-901d-a1547929137a.png)

- [x] When a New GitHub Milestone is created, create a Pivotal Epic.

	> ![Screen Shot 2020-01-31 at 4 35 57 PM](https://user-images.githubusercontent.com/15182/73583591-f01caf80-4447-11ea-9e29-d5800f68b3af.png)

- [x] When a GitHub Issue is assigned to a GitHub MileStone, assign Pivotal Story to Epic.

- [x] When a GitHub Milestone is updated, update Pivotal Epic.

**Comment by ericclemmons** [comment]
@sammartinez Yes, I am ;)

> ![Screen Shot 2020-01-29 at 4 15 27 PM](https://user-images.githubusercontent.com/15182/73408950-9fc01900-42b2-11ea-800d-fd78bcceeaff.png)

**Comment by ericclemmons** [comment]
Issues are only created once now, by `external_id`:
> ![Screen Shot 2020-01-30 at 3 28 07 PM](https://user-images.githubusercontent.com/15182/73499991-7668c100-4376-11ea-9b4e-d363ce693ff9.png)

Issues now have external links and also a special icon:
> ![Screen Shot 2020-01-30 at 3 39 42 PM](https://user-images.githubusercontent.com/15182/73500119-c182d400-4376-11ea-8afd-babb25ab0df8.png)
> ![Screen Shot 2020-01-30 at 3 38 13 PM](https://user-images.githubusercontent.com/15182/73500033-8d0f1800-4376-11ea-8861-bb1272d45ea7.png)

**Comment by ericclemmons** [comment]
Milestone creation & issue adding is working:
> ![Screen Shot 2020-01-31 at 4 35 57 PM](https://user-images.githubusercontent.com/15182/73583591-f01caf80-4447-11ea-9e29-d5800f68b3af.png)

**Comment by ericclemmons** [comment]
The prototype is up & running: https://www.pivotaltracker.com/n/projects/2431346

This is powered by https://github.com/ericclemmons/sync-github-pivotal.

Knowing what I know today, I **do not** believe that GitHub and Pivotal should be synced 1-to-1, at least in the state GitHub is today.

My take is that GitHub issues are great for gathering input, but not as making work _actionable_.

Discussions may be better for defining _how_ work is done in the open, and perhaps that should be synced to Pivotal instead.

That would give us a clean slate for Pivotal & GitHub to _both_ be in sync, acting as a public roadmap with priorities & votes, as well as "answers" for how we're going to tackle the problem and execute.

More thinking and testing to be done here, but I'm seeing more effort to organize GitHub Issues in Pivotal than copy/pasting Milestone titles with @samlmar .
