### ISSUE TITLE
Amplify push creates empty schema file, overriding schema dir

### ISSUE THREAD

**Issue by clintfoster** [aws-amplify/amplify-js#9523]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
# Unfortunately the script failed, as follows:
% npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages
undefined:5
<% if (pkg.author) { %>  "author": <%= JSON.stringify(pkg.author) %>,<% } %>
^

SyntaxError: Unexpected token < in JSON at position 109
    at JSON.parse (<anonymous>)
    at xxx/node_modules/envinfo/dist/envinfo.js:1:1715
    at async Promise.all (index 8)
    at async Promise.all (index 1)
    at async Promise.all (index 1)
    at async Promise.all (index 20)

```

</details>

### Describe the bug

When I take an existing project and break up `schema.graphql` into multiple files under `schema/` they compile correctly. But `push` fails because it creates an empty `schema.graphql`.

Compilation:

```
% amplify api gql-compile                                                                  
GraphQL schema compiled successfully.

Edit your schema at amplify/backend/api/MyApi/schema.graphql or place .graphql files in a directory at amplify/backend/api/MyApi/schema
```

I verified the compile worked because the generated `build/graphql.schema`  has the combined schemas from the separate files.

However, when I ran `amplify push` I got the following error:

>✖ An error occurred when pushing the resources to the cloud
>🛑 An error occurred during the push operation: Syntax Error: Unexpected EOF

I see `push` created an empty `schema.graphql`, causing the error above.

At this point if I run  `gql-compile` again it returns the error too unless I delete the empty `schema.graphql`.

## Workaround
I noticed that the empty file was created between answering the following two prompts during `push`:

```
This version of Amplify CLI introduces additional security enhancements for your GraphQL API. @auth authorization rules applied on primary keys and indexes are scoped down further. The changes are applied automatically with this deployment. This change won't impact your client code. Continue (Y/n) › Y

(Watching the file system I see the empty file is created here.)

 Successfully pulled backend environment dev from the cloud.

 (Shows changes to be pushed)

 Are you sure you want to continue? (Y/n) 
```

By deleting the empty file before answering the second question I am able to get the push to complete successfully.

### Expected behavior

`push` should recognize the `MyApi/schema` directory is populated with schema files, and use it rather than generating an empty `MyApi/schema.graphql`.

### Reproduction steps

I tried it with a simple project containing only two schema files (`todo.graphql` & `test.graphql`), as shown below. However, it did not repro, possibly because I did not receive the prompt mentioned earlier:

>This version of Amplify CLI introduces additional security enhancements 

It was immediately after this prompt that the empty file was created. I'm not sure how to force this logic path without the full project.

## Simple project (doesn't repro)

1. Create `schema-test` dir & cd to it
1. `amplify init` & accept defaults
1. `amplify add api`, answering "N" to edit schema
1. `cd amplify/backend/api/schematest `
1. `rm schema.graphql`
1. `mkdir schema`
1. Place two trivial schema files in dir, e.g.:

### todo.graphql
```
type Todo @model {
  id: ID!
  name: String
}
```

### test.graphql
```
type Test @model {
  id: ID!
  name: String
}
```

Running `amplify api gql-compile` compiles the two schema files correctly, as with the real project.

However, unlike the real project, I don't get the above prompt when I `push`, and the empty `schema.graphql` isn't created. So the push succeeds with this simple example.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @clintfoster 👋 thanks for raising this issue. Because it is related to the CLI, I'm transferring this over to the CLI repo for better support.
