### ISSUE TITLE
Improve developer experience for handling subscriptions, WebSocket connections, etc (GraphQL, PubSub, etc)

### ISSUE THREAD

**Issue by chrisbonifacio** [aws-amplify/amplify-js#9824]
### Is this related to a new or existing API?

GraphQL API, PubSub

### Describe the feature you'd like to request

Many customers have reported several issues with GraphQL/PubSub subscriptions. Opening this feature request to consolidate the issues for simpler context searching and facilitate community discussion for workarounds and/or guidance from the team.

Related issues:

- [ ] https://github.com/aws-amplify/amplify-js/issues/3039 - PubSub reconnect (highest customer activity)
- [x] https://github.com/aws-amplify/amplify-js/issues/9818 - no callback triggered when WebSocket connection is closed
- [ ] https://github.com/aws-amplify/amplify-js/issues/9805 - `unsubscribe()` does not trigger `complete` callback on signout
- [ ] https://github.com/aws-amplify/amplify-js/issues/9749 - unable to reconnect after network interruption
- [ ] https://github.com/aws-amplify/amplify-js/issues/9185 - needing to patch `paho-mqtt` package
- [x] https://github.com/aws-amplify/amplify-js/issues/4733 - subscriptions sometimes fail, no way to detect
- [ ] https://github.com/aws-amplify/amplify-js/issues/4459 - how do I detect if WebSocket closed and reconnect?
- [x] https://github.com/aws-amplify/amplify-js/issues/6064 - feature request for `subscribe` callback (observer accepts `start` but not triggered on connection/start_ack?)
- [ ] https://github.com/aws-amplify/amplify-js/issues/7156 - force close existing WebSocket connections when calling `Amplify.configure`
- [x] https://github.com/aws-amplify/amplify-js/issues/2692 - how do I catch PubSub errors if MQTT connection is lost or broken?

### Describe the solution you'd like

- [ ] WebSocket reconnection would be handled automatically by our library.
- [ ] Expose the closed connections through the `error` callback (at the moment, we do see some network errors such as `timeout disconnect`).
- [ ] Expose whether unsubscribing was successful either by accepting callbacks for `unsubscribe` or through the observer's `complete` callback, etc.

### Describe alternatives you've considered

List of Workarounds or PRs:

API GraphQL: A PR was merged to expose network errors and address https://github.com/aws-amplify/amplify-js/issues/1448 but maybe we can provide guidance or an example on how to handle re-subscribing when this error occurs.

React Native PubSub workaround using AppState (Shared by Customer): https://github.com/aws-amplify/amplify-js/issues/3039#issuecomment-1025399327

MQTT IOT Reconnect (Shared by Customer): https://github.com/aws-amplify/amplify-js/issues/3039#issuecomment-599365164

### Additional context

Recently I tried using `API.graphql.subscribe` and noticed that I couldn't get `start` or `complete` callbacks to be invoked.

```js
  function subscribe() {
    API.graphql({ query: onCreateTodo }).subscribe({
      start: () => console.log("subscription started"),
      next: (data) => console.log("sub update:", data),
      error: (err) => console.log("sub error:", err),
      complete: (e) => console.log("sub complete:", e),
    });
  }
```
socket updates

<img width="1105" alt="Screen Shot 2022-04-20 at 11 20 54 AM" src="https://user-images.githubusercontent.com/16952986/164276563-89272c47-1a9c-458c-b30b-77c4aab7b15b.png">

console logs (only `next` and `error` (handshake, timeout, etc) are called)

<img width="1451" alt="Screen Shot 2022-04-20 at 12 26 46 PM" src="https://user-images.githubusercontent.com/16952986/164278400-6085485c-9823-4e67-974c-a962eb2e5783.png">

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by stocaaro** [comment]
Reconnection is now staged on the `next` tag in preparation for release in aws-amplify v5. To test against this update install the `next` tag version of the aws-amplify packages your project is using. eg `yarn add aws-amplify@next`.

With this change any disrupted connection will attempt to reconnect when possible. Reconnection can be expected to trigger 5 seconds after the resources to reconnect are available. If the network is disrupted in a way that can't be detected, reconnection will be attempted every minute until the connection is recovered.

Note that missed messages will not backfill on recovery. If you need to trigger behavior to catch up missed messaged on recovery, this should be possible to implement using the connection state Hub messages released last month.
https://docs.amplify.aws/lib/pubsub/subunsub/q/platform/js/#unsubscribe
https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/js/#subscription-connection-status-updates

**Comment by stocaaro** [comment]
Good news. Automated Reconnection is now available on the latest `aws-amplify` release! Review the updated subscription docs for [API](https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/js/#connection-issues-and-automated-reconnection) / [PubSub](https://docs.amplify.aws/lib/pubsub/subunsub/q/platform/js/#connection-issues-and-automated-reconnection) and consider any application behavior you may want to add to best meet your users needs when subscriptions reconnect.

Please review our [breaking change guidance](https://github.com/aws-amplify/amplify-js#notice) before upgrading your application.

To upgrade Amplify to version 5, run the following in your project folder:
```
yarn add aws-amplify@latest
```

Check `package.json` to see if your project uses other `@aws-amplify/*` packages directly and upgrade them to latest as well.

With this behavior released, I am closing this issue as resolved.

**Comment by stocaaro** [comment]
Note, there are a few other issues listed here that will be solved independent of the core Connection State / Reconnection issue.

**Comment by pfried** [comment]
I think there is an error in the docs (api + pubsub): https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/js/#subscription-connection-status-updates

The value compared to should be `payload.data.connectionState` and not `payload.message`

The code works tough but either it is the wrong field or type. (Would not have happened if the HubEvents were typed 😉)
